### ISSUE TITLE
Typing "it's" changes to "said"

### ISSUE THREAD

**Issue by heldtogether** [atmb4u/AutoJS#3]
If you type in the entire word "it's" (with the apostrophe), the word is changed to "said".

**Comment by zekenie** [comment]
The same thing is happening with "I'm" ... might it be an escaping ' character issue?

**Comment by heldtogether** [comment]
My guess is that the library doesn't expect any word to be a contraction. To get around this issue, any word containing an apostrophe could be ignored and not tried to be changed.

**Comment by joenall** [comment]
If you start the text entry with a "  (e.g. "now"), the resulting text is incorrect.

**Comment by mikeful** [comment]
Same issue with "I'd" -> "day".

**Comment by atmb4u** [comment]
Thanks a lot on the creative energy fellas! #inspired.
All these issues are fixed.
