### ISSUE TITLE
Ompletelty un nusable in urrent orm. Inner-word symbols results in start of word deletion.

### ISSUE THREAD

**Issue by williamsharkey** [atmb4u/AutoJS#4]
If I type "auto-complete", the output is "omplete"

Using FF 25.0.1 on Win XP 32.

**Comment by nwalke** [comment]
Go try it now.  I think they just updated the code to allow for symbols.  http://atmb4u.github.io/AutoJS/

**Comment by atmb4u** [comment]
Exactly @tubaguy50035. This issue is fixed now. Thanks for the ticket @williamsharkey. Appreciate your effort.
