### ISSUE TITLE
Demo doesn't work. Wrong link.

### ISSUE THREAD

**Issue by LarryBattle** [atmb4u/AutoJS#5]
The demo doesn't work on http://atmb4u.github.io/AutoJS/, because the url link for auto.micro.min.js is wrong.

`"https://rawgithub.com/atmb4u/AutoJS/master/auto.micro.min.js"`
should be 
`"https://raw.github.com/atmb4u/AutoJS/master/auto.micro.min.js"`

**Comment by atmb4u** [comment]
This is not a bug. That's the url from github for serving files, else github pages would complain for mimetype.

**Comment by LarryBattle** [comment]
I think you didn't see the dot that's missing.
Anyhow here's why I filed the bug. Both Chrome 30 and Firefox 25.0 are both telling me that the url is invalid, which is causing me to get this error message.
`Uncaught ReferenceError: AutoSuggestControl is not defined`

Firefox:
`[14:40:07.998] GET https://rawgithub.com/atmb4u/AutoJS/master/auto.max.min.js [HTTP/1.1 503 Service Unavailable 0ms]`

Chrome:
`GET https://rawgithub.com/atmb4u/AutoJS/master/auto.max.min.js`

I think you might need to update your demo on http://atmb4u.github.io/AutoJS/ to match the demo in the repository. Maybe that's the issue.

**Comment by atmb4u** [comment]
http://stackoverflow.com/questions/6551446/can-i-run-html-files-directly-from-github-instead-of-just-viewing-their-source
This is where I got the idea.
Can someone else replicate this issue?

**Comment by LarryBattle** [comment]
From the github project page for http://rawgithub.com/

```
What will happen if I hotlink to a rawgithub.com URL on a production website?

Bad things. If you hotlink to a rawgithub.com URL on a site that gets lots of traffic, requests will be throttled. 
If this heavy traffic continues, requests originating from your site will eventually be dropped. 
```

So my assumption is that after your project got posted on hacker news and visitors viewed your demo, the rawgithub.com links reached their limit and went down.

Solution: 
Use github pages to host your demo.

Github pages:
http://pages.github.com/

Creating Github pages manually.
https://help.github.com/articles/creating-project-pages-manually

**Comment by atmb4u** [comment]
We are already using github pages. Works well now.
